image: gcc:9

build:
  stage: build
  before_script:
    - apt update && apt -y install bison flex bc
    - make O=build defconfig
  script:
    - make O=build Image
  artifacts:
    paths:
      - build/arch/arm64/boot/Image
  cache:
    paths:
      - build
