image: gcc:9

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  before_script:
    - apt update && apt -y install bison flex bc
      # - git submodule update --recursive --remote --force
    - make O=build defconfig
    - sed -i -- 's/# CONFIG_MMC_SDHCI_PCI is not set/CONFIG_MMC_SDHCI_PCI=y/g' build/.config
    - sed -i -- 's/# CONFIG_NE2K_PCI is not set/CONFIG_NE2K_PCI=y/g' build/.config
    - sed -i -- 's/# CONFIG_8139CP is not set/CONFIG_8139CP=y/g' build/.config
    - sed -i -- 's/# CONFIG_SND_ENS1370 is not set/CONFIG_SND_ENS1370=y/g' build/.config
    - sed -i -- 's/# CONFIG_SND_SOC_AC97_CODEC is not set/CONFIG_SND_SOC_AC97_CODEC=y/g' build/.config
    - sed -i -- 's/CONFIG_RFKILL=m/CONFIG_RFKILL=y/g' build/.config
    - sed -i -- 's/CONFIG_CFG80211=m/CONFIG_CFG80211=y/g' build/.config
    - sed -i -- 's/CONFIG_BRCMFMAC=m/CONFIG_BRCMFMAC=y/g' build/.config
    - sed -i -- 's/# CONFIG_SQUASHFS_XZ is not set/CONFIG_SQUASHFS_XZ=y/g' build/.config
    - sed -i -- 's/# CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES is not set/CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y/g' build/.config
    - rm -rf build/arch/arm64/boot/Image
  script:
    - make -j 2 O=build Image modules_prepare
  artifacts:
    paths:
      - build/arch/arm64/boot/Image
  cache:
    paths:
      - build
