name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: defconfig
      run: make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=build defconfig
    - name: make
      run: make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=build Image modules_prepare

    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel
        path: build/arch/arm64/boot/Image
